# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "ros2_control hardware interface for Feetech Servos"
AUTHOR = "Jafar Uruc <jafar.uruc@gmail.com>"
HOMEPAGE = "https://github.com/JafarAbdi/feetech_ros2_driver"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=8;endline=8;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "feetech_ros2_driver"
ROS_BPN = "feetech_ros2_driver"

ROS_BUILD_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-libserial-dev} \
    fmt \
    hardware-interface \
    pkgconfig \
    pluginlib \
    range-v3 \
    rclcpp \
    spdlog \
    tl-expected \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-libserial-dev} \
    fmt \
    hardware-interface \
    pkgconfig \
    pluginlib \
    range-v3 \
    rclcpp \
    spdlog \
    tl-expected \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    action-msgs \
    ament-index-cpp \
    builtin-interfaces \
    class-loader \
    control-msgs \
    geometry-msgs \
    libstatistics-collector \
    libtinyxml2 \
    libyaml \
    libyaml-vendor \
    lifecycle-msgs \
    rcl \
    rcl-interfaces \
    rcl-logging-interface \
    rcl-logging-spdlog \
    rcl-yaml-param-parser \
    rclcpp-lifecycle \
    rcpputils \
    rcutils \
    rmw \
    rmw-implementation \
    rmw-implementation-cmake \
    rosgraph-msgs \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-interface \
    sensor-msgs \
    statistics-msgs \
    std-msgs \
    tinyxml2-vendor \
    tracetools \
    trajectory-msgs \
    unique-identifier-msgs \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-interfaces-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-python-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-package-native \
    cmake-native \
    python3-catkin-pkg-native \
    python3-importlib-metadata-native \
    python3-native \
    python3-setuptools-native \
"

ROS_EXEC_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-libserial-dev} \
    fmt \
    hardware-interface \
    pkgconfig \
    pluginlib \
    range-v3 \
    rclcpp \
    spdlog \
    tl-expected \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/feetech_ros2_driver-release/archive/release/humble/feetech_ros2_driver/0.1.0-2.tar.gz
ROS_BRANCH ?= "branch=release/humble/feetech_ros2_driver"
SRC_URI = "git://github.com/ros2-gbp/feetech_ros2_driver-release;${ROS_BRANCH};protocol=https"
SRCREV = "55a0b011607f2c9cb5189ace568c9387b06b5fd4"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
