# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_lyrical
inherit ros_superflore_generated

DESCRIPTION = "RTAB-Map's various useful nodes and nodelets."
AUTHOR = "Mathieu Labbe <matlabbe@gmail.com>"
ROS_AUTHOR = "Mathieu Labbe"
HOMEPAGE = "https://github.com/introlab/rtabmap_ros/issues"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=9;endline=9;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "rtabmap_ros"
ROS_BPN = "rtabmap_util"

ROS_BUILD_DEPENDS = "\
    cv-bridge \
    image-geometry \
    image-transport \
    laser-geometry \
    message-filters \
    nav-msgs \
    octomap-msgs \
    pcl-conversions \
    pcl-ros \
    rclcpp \
    rclcpp-components \
    ros-environment \
    rtabmap-conversions \
    rtabmap-msgs \
    rtabmap-sync \
    sensor-msgs \
    std-msgs \
    stereo-msgs \
    tf2 \
    tf2-geometry-msgs \
    tf2-ros \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    cv-bridge \
    image-geometry \
    image-transport \
    laser-geometry \
    message-filters \
    nav-msgs \
    octomap-msgs \
    pcl-conversions \
    pcl-ros \
    rclcpp \
    rclcpp-components \
    rtabmap-conversions \
    rtabmap-msgs \
    rtabmap-sync \
    sensor-msgs \
    std-msgs \
    stereo-msgs \
    tf2 \
    tf2-geometry-msgs \
    tf2-ros \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-liboctomap-dev} \
    action-msgs \
    ament-index-cpp \
    builtin-interfaces \
    class-loader \
    composition-interfaces \
    diagnostic-msgs \
    diagnostic-updater \
    fastcdr \
    gcc-runtime \
    geometry-msgs \
    gtsam \
    keyboard-handler \
    libeigen \
    libg2o \
    libstatistics-collector \
    libtinyxml2 \
    libyaml \
    libyaml-vendor \
    lttng-ust \
    opencv \
    orocos-kdl \
    pcl \
    pcl-msgs \
    pluginlib \
    python3-deprecated \
    python3-numpy \
    qt-gui-cpp \
    qtbase \
    rcl \
    rcl-action \
    rcl-interfaces \
    rcl-logging-implementation \
    rcl-logging-interface \
    rcl-logging-spdlog \
    rcl-yaml-param-parser \
    rclcpp-action \
    rclpy \
    rcpputils \
    rcutils \
    rmw \
    rmw-implementation \
    rmw-implementation-cmake \
    rosbag2-compression \
    rosbag2-cpp \
    rosbag2-interfaces \
    rosbag2-storage \
    rosbag2-transport \
    rosgraph-msgs \
    rosidl-buffer \
    rosidl-buffer-backend \
    rosidl-buffer-py \
    rosidl-cmake \
    rosidl-core-runtime \
    rosidl-dynamic-typesupport \
    rosidl-generator-py \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-fastrtps-c \
    rosidl-typesupport-fastrtps-cpp \
    rosidl-typesupport-interface \
    rosidl-typesupport-introspection-c \
    rosidl-typesupport-introspection-cpp \
    rtabmap \
    service-msgs \
    sqlite3 \
    statistics-msgs \
    std-srvs \
    tbb \
    tf2-eigen \
    tf2-msgs \
    tracetools \
    type-description-interfaces \
    unique-identifier-msgs \
    visualization-msgs \
    yaml-cpp \
    yaml-cpp-vendor \
    zlib \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-python-native \
    ament-cmake-ros-core-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-index-python-native \
    ament-package-native \
    cmake-native \
    eigen3-cmake-module-native \
    gcc-runtime-native \
    pkgconfig-native \
    python3-catkin-pkg-native \
    python3-empy-native \
    python3-native \
    python3-setuptools-native \
    rcpputils-native \
    rcutils-native \
    rosidl-buffer-native \
    rosidl-cmake-native \
    rosidl-generator-c-native \
    rosidl-generator-cpp-native \
    rosidl-generator-type-description-native \
    rosidl-pycommon-native \
    rosidl-runtime-c-native \
    rosidl-runtime-cpp-native \
    rosidl-typesupport-c-native \
    rosidl-typesupport-interface-native \
"

ROS_EXEC_DEPENDS = "\
    cv-bridge \
    image-geometry \
    image-transport \
    laser-geometry \
    message-filters \
    nav-msgs \
    octomap-msgs \
    pcl-conversions \
    pcl-ros \
    rclcpp \
    rclcpp-components \
    rtabmap-conversions \
    rtabmap-msgs \
    rtabmap-sync \
    sensor-msgs \
    std-msgs \
    stereo-msgs \
    tf2 \
    tf2-geometry-msgs \
    tf2-ros \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/introlab/rtabmap_ros-release/archive/release/lyrical/rtabmap_util/0.23.7-1.tar.gz
ROS_BRANCH ?= "branch=release/lyrical/rtabmap_util"
SRC_URI = "git://github.com/introlab/rtabmap_ros-release;${ROS_BRANCH};protocol=https"
SRCREV = "67b9e577ddc3a3874ebeb38ea1ce56323ae92ca7"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
