GO_MOD_LICENSES = "Apache-2.0 & MIT & Unknown"

LIC_FILES_CHKSUM  += "${VENDORED_LIC_FILES_CHKSUM}"
VENDORED_LIC_FILES_CHKSUM = "\
    file://src/${GO_IMPORT}/vendor/github.com/charlievieth/fastwalk/LICENSE;md5=ca768dcff348a2a95cf861f3312b0a5c \
    file://src/${GO_IMPORT}/vendor/github.com/charlievieth/fastwalk/go.LICENSE;md5=5d4950ecb7b26d2c5e4e7b4e0dd74707 \
    file://src/${GO_IMPORT}/vendor/github.com/gdamore/encoding/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57 \
    file://src/${GO_IMPORT}/vendor/github.com/gdamore/tcell/v2/LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57 \
    file://src/${GO_IMPORT}/vendor/github.com/junegunn/go-shellwords/LICENSE;md5=e5116fc268f5118168ff06a271b50ef9 \
    file://src/${GO_IMPORT}/vendor/github.com/lucasb-eyer/go-colorful/LICENSE;md5=00a5466a69069b14448ded7ed1f3125f \
    file://src/${GO_IMPORT}/vendor/github.com/mattn/go-isatty/LICENSE;md5=f509beadd5a11227c27b5d2ad6c9f2c6 \
    file://src/${GO_IMPORT}/vendor/github.com/mattn/go-runewidth/LICENSE;md5=24ce168f90aec2456a73de1839037245 \
    file://src/${GO_IMPORT}/vendor/github.com/rivo/uniseg/LICENSE.txt;md5=4393c339bf180cf6e188b6ea32d8b93c \
    file://src/${GO_IMPORT}/vendor/golang.org/x/sys/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a \
    file://src/${GO_IMPORT}/vendor/golang.org/x/term/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a \
    file://src/${GO_IMPORT}/vendor/golang.org/x/text/LICENSE;md5=7998cb338f82d15c0eff93b7004d272a \
"
