# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_jazzy
inherit ros_superflore_generated

DESCRIPTION = "An example node using the jig system."
AUTHOR = "Alistair English <hello@alistairenglish.com>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
# Original license in package.xml, joined with "AND" when multiple license tags were used:
#         "Apache 2.0"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=8;endline=8;md5=3dce4ba60d7e51ec64f3c3dc18672dd3"

ROS_CN = "jig"
ROS_BPN = "jig_example"

ROS_BUILD_DEPENDS = "\
    example-interfaces \
    geometry-msgs \
    jig \
    rclcpp \
    rclpy \
    std-msgs \
    std-srvs \
"

ROS_BUILDTOOL_DEPENDS = ""

ROS_EXPORT_DEPENDS = "\
    example-interfaces \
    geometry-msgs \
    jig \
    rclcpp \
    rclpy \
    std-msgs \
    std-srvs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = "\
    example-interfaces \
    geometry-msgs \
    jig \
    rclcpp \
    rclpy \
    std-msgs \
    std-srvs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    launch-ros \
    launch-testing \
    launch-testing-ament-cmake \
    lifecycle-msgs \
    rcl-interfaces \
    tf2-msgs \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/jig-release/archive/release/jazzy/jig_example/0.0.2-1.tar.gz
ROS_BRANCH ?= "branch=release/jazzy/jig_example"
SRC_URI = "git://github.com/ros2-gbp/jig-release;${ROS_BRANCH};protocol=https"
SRCREV = "fb313bdb4701326f8526c7c59efbdf141d535937"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
