# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "ROS package to interface with IIO devices"
AUTHOR = "Analog Devices <adrian.suciu@analog.com>"
ROS_AUTHOR = "Adrian Suciu <adrian.suciu@analog.com>"
HOMEPAGE = "https://analogdevicesinc.github.io/iio_ros2/"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "Apache License, Version 2.0"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=8;endline=8;md5=e8978a5103d23266fc6f8ec03dc9eb16"

ROS_CN = "adi_iio"
ROS_BPN = "adi_iio"

ROS_BUILD_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-libiio-dev} \
    rclcpp \
    rosidl-typesupport-introspection-cpp \
    std-msgs \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
    rosidl-default-generators-native \
"

ROS_EXPORT_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-libiio-dev} \
    rclcpp \
    rosidl-typesupport-introspection-cpp \
    std-msgs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    ament-index-cpp \
    builtin-interfaces \
    libstatistics-collector \
    libyaml \
    libyaml-vendor \
    rcl \
    rcl-interfaces \
    rcl-logging-interface \
    rcl-logging-spdlog \
    rcl-yaml-param-parser \
    rcpputils \
    rcutils \
    rmw \
    rmw-implementation \
    rmw-implementation-cmake \
    rosgraph-msgs \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-interface \
    statistics-msgs \
    tracetools \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-interfaces-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-gmock-native \
    ament-cmake-gtest-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-pytest-native \
    ament-cmake-python-native \
    ament-cmake-ros-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-index-python-native \
    ament-package-native \
    cmake-native \
    domain-coordinator-native \
    fastcdr-native \
    fastrtps-cmake-module-native \
    gmock-vendor-native \
    gtest-native \
    gtest-vendor-native \
    python-cmake-module-native \
    python3-catkin-pkg-native \
    python3-empy-native \
    python3-importlib-metadata-native \
    python3-native \
    python3-pytest-native \
    python3-setuptools-native \
    rcpputils-native \
    rcutils-native \
    rmw-native \
    ros-environment-native \
    rosidl-cmake-native \
    rosidl-generator-c-native \
    rosidl-generator-cpp-native \
    rosidl-generator-py-native \
    rosidl-generator-rs-native \
    rosidl-runtime-c-native \
    rosidl-runtime-cpp-native \
    rosidl-typesupport-c-native \
    rosidl-typesupport-cpp-native \
    rosidl-typesupport-fastrtps-c-native \
    rosidl-typesupport-fastrtps-cpp-native \
    rosidl-typesupport-interface-native \
    rosidl-typesupport-introspection-c-native \
    rosidl-typesupport-introspection-cpp-native \
"

ROS_EXEC_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-libiio-dev} \
    rclcpp \
    ros2launch \
    rosidl-default-runtime \
    rosidl-typesupport-introspection-cpp \
    std-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-cmake-cppcheck \
    ament-cmake-cpplint \
    ament-cmake-lint-cmake \
    ament-cmake-ros \
    ament-cmake-xmllint \
    ament-copyright \
    ament-lint-auto \
    ament-lint-common \
    ament-pep257 \
    launch \
    launch-pytest \
    launch-ros \
    launch-testing \
    launch-testing-ament-cmake \
    python3-scipy \
    rclpy \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/adi_iio-release/archive/release/humble/adi_iio/1.0.1-3.tar.gz
ROS_BRANCH ?= "branch=release/humble/adi_iio"
SRC_URI = "git://github.com/ros2-gbp/adi_iio-release;${ROS_BRANCH};protocol=https"
SRCREV = "e23aa1192f7333106e6c49ededa203db9045f451"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
