# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_lyrical
inherit ros_superflore_generated

DESCRIPTION = "An almost dependency-less library for converting between color spaces"
AUTHOR = "David V. Lu!! <david@metrorobots.com>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=8;endline=8;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "color_util"
ROS_BPN = "color_util"

ROS_BUILD_DEPENDS = "\
    std-msgs \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
    ament-cmake-python-native \
"

ROS_EXPORT_DEPENDS = "\
    std-msgs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    builtin-interfaces \
    fastcdr \
    rcpputils \
    rcutils \
    rmw \
    rosidl-buffer \
    rosidl-buffer-backend \
    rosidl-buffer-py \
    rosidl-cmake \
    rosidl-core-runtime \
    rosidl-dynamic-typesupport \
    rosidl-generator-py \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-fastrtps-c \
    rosidl-typesupport-fastrtps-cpp \
    rosidl-typesupport-interface \
    rosidl-typesupport-introspection-c \
    rosidl-typesupport-introspection-cpp \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-ros-core-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-index-python-native \
    ament-package-native \
    cmake-native \
    python3-catkin-pkg-native \
    python3-empy-native \
    python3-native \
    python3-setuptools-native \
    rcpputils-native \
    rcutils-native \
    rosidl-buffer-native \
    rosidl-cmake-native \
    rosidl-generator-c-native \
    rosidl-generator-cpp-native \
    rosidl-generator-type-description-native \
    rosidl-pycommon-native \
    rosidl-runtime-c-native \
    rosidl-runtime-cpp-native \
    rosidl-typesupport-c-native \
    rosidl-typesupport-interface-native \
"

ROS_EXEC_DEPENDS = "\
    std-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-cmake-gtest \
    ament-cmake-pytest \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/color_util-release/archive/release/lyrical/color_util/1.2.0-2.tar.gz
ROS_BRANCH ?= "branch=release/lyrical/color_util"
SRC_URI = "git://github.com/ros2-gbp/color_util-release;${ROS_BRANCH};protocol=https"
SRCREV = "bd405b3671689b37d4038da7229e6db8e98692b6"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
