# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "A Qt-JS application for visualisation of executing/log-replayed behaviour trees in a ROS2 ecosystem."
AUTHOR = "Daniel Stonier <d.stonier@gmail.com>"
ROS_AUTHOR = "Daniel Stonier <d.stonier@gmail.com>"
HOMEPAGE = "https://github.com/splintered-reality/py_trees_ros_viewer"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=14;endline=14;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "py_trees_ros_viewer"
ROS_BPN = "py_trees_ros_viewer"

ROS_BUILD_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-pyqt5-dev-tools} \
    python3-setuptools \
    qttools \
"

ROS_BUILDTOOL_DEPENDS = ""

ROS_EXPORT_DEPENDS = ""

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = ""

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = "\
    py-trees-js \
    py-trees-ros-interfaces \
    python3-pyqt5 \
    rclpy \
    unique-identifier-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/py_trees_ros_viewer-release/archive/release/humble/py_trees_ros_viewer/0.3.0-1.tar.gz
ROS_BRANCH ?= "branch=release/humble/py_trees_ros_viewer"
SRC_URI = "git://github.com/ros2-gbp/py_trees_ros_viewer-release;${ROS_BRANCH};protocol=https"
SRCREV = "bfdd484a958b44a2520ae7717394727e70018bd2"

ROS_BUILD_TYPE = "ament_python"

inherit ros_${ROS_BUILD_TYPE}
