# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "These are lightweight text streaming classes that connect to standardised      ecl type devices."
AUTHOR = "Daniel Stonier <d.stonier@gmail.com>"
ROS_AUTHOR = "Daniel Stonier <d.stonier@gmail.com>"
HOMEPAGE = "http://wiki.ros.org/ecl_streams"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=10;endline=10;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "ecl_core"
ROS_BPN = "ecl_streams"

ROS_BUILD_DEPENDS = "\
    ecl-build \
    ecl-concepts \
    ecl-converters \
    ecl-devices \
    ecl-errors \
    ecl-license \
    ecl-time \
    ecl-type-traits \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-ros-native \
"

ROS_EXPORT_DEPENDS = ""

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = ""

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-interfaces-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-gmock-native \
    ament-cmake-gtest-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-native \
    ament-cmake-pytest-native \
    ament-cmake-python-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-package-native \
    cmake-native \
    domain-coordinator-native \
    gmock-vendor-native \
    gtest-native \
    gtest-vendor-native \
    python3-catkin-pkg-native \
    python3-importlib-metadata-native \
    python3-native \
    python3-pytest-native \
    python3-setuptools-native \
"

ROS_EXEC_DEPENDS = "\
    ecl-concepts \
    ecl-converters \
    ecl-devices \
    ecl-errors \
    ecl-license \
    ecl-time \
    ecl-type-traits \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-cmake-gtest \
    ament-lint-auto \
    ament-lint-common \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/ecl_core-release/archive/release/humble/ecl_streams/1.2.1-1.tar.gz
ROS_BRANCH ?= "branch=release/humble/ecl_streams"
SRC_URI = "git://github.com/ros2-gbp/ecl_core-release;${ROS_BRANCH};protocol=https"
SRCREV = "eafc3a3c073aca357af8137b2896f8e1f6285dea"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
