# Copyright (c) 2019 LG Electronics, Inc.

# /jenkins/mjansa/build-ros-v3/artifacts/BUILD-webos-eloquent-master.mcf/work/raspberrypi3-webos-linux-gnueabi/ecl-sigslots/1.0.4-1-r0/git/src/examples/../../include/ecl/sigslots/signal.hpp:179:11: error: implicitly-declared 'constexpr ecl::Signal<ecl::Void>& ecl::Signal<ecl::Void>::operator=(const ecl::Signal<ecl::Void>&)' is deprecated [-Werror=deprecated-copy]
# /jenkins/mjansa/build-ros-v3/artifacts/BUILD-webos-eloquent-master.mcf/work/raspberrypi3-webos-linux-gnueabi/ecl-sigslots/1.0.4-1-r0/git/src/examples/../../include/ecl/sigslots/slot.hpp:243:11: error: implicitly-declared 'constexpr ecl::Slot<ecl::Void>& ecl::Slot<ecl::Void>::operator=(const ecl::Slot<ecl::Void>&)' is deprecated [-Werror=deprecated-copy]
# /jenkins/mjansa/build-ros-v3/artifacts/BUILD-webos-eloquent-master.mcf/work/raspberrypi3-webos-linux-gnueabi/ecl-sigslots/1.0.4-1-r0/git/src/examples/../../include/ecl/sigslots/signal.hpp:179:11: error: implicitly-declared 'constexpr ecl::Signal<ecl::Void>& ecl::Signal<ecl::Void>::operator=(const ecl::Signal<ecl::Void>&)' is deprecated [-Werror=deprecated-copy]
# /jenkins/mjansa/build-ros-v3/artifacts/BUILD-webos-eloquent-master.mcf/work/raspberrypi3-webos-linux-gnueabi/ecl-sigslots/1.0.4-1-r0/git/src/examples/../../include/ecl/sigslots/slot.hpp:243:11: error: implicitly-declared 'constexpr ecl::Slot<ecl::Void>& ecl::Slot<ecl::Void>::operator=(const ecl::Slot<ecl::Void>&)' is deprecated [-Werror=deprecated-copy]
# /jenkins/mjansa/build-ros-v3/artifacts/BUILD-webos-eloquent-master.mcf/work/raspberrypi3-webos-linux-gnueabi/ecl-sigslots/1.0.4-1-r0/git/src/examples/../../include/ecl/sigslots/signal.hpp:179:11: error: implicitly-declared 'constexpr ecl::Signal<ecl::Void>& ecl::Signal<ecl::Void>::operator=(const ecl::Signal<ecl::Void>&)' is deprecated [-Werror=deprecated-copy]
# /jenkins/mjansa/build-ros-v3/artifacts/BUILD-webos-eloquent-master.mcf/work/raspberrypi3-webos-linux-gnueabi/ecl-sigslots/1.0.4-1-r0/git/src/examples/../../include/ecl/sigslots/slot.hpp:243:11: error: implicitly-declared 'constexpr ecl::Slot<ecl::Void>& ecl::Slot<ecl::Void>::operator=(const ecl::Slot<ecl::Void>&)' is deprecated [-Werror=deprecated-copy]
# /jenkins/mjansa/build-ros-v3/artifacts/BUILD-webos-eloquent-master.mcf/work/raspberrypi3-webos-linux-gnueabi/ecl-sigslots/1.0.4-1-r0/git/src/examples/../../include/ecl/sigslots/signal.hpp:179:11: error: implicitly-declared 'constexpr ecl::Signal<ecl::Void>& ecl::Signal<ecl::Void>::operator=(const ecl::Signal<ecl::Void>&)' is deprecated [-Werror=deprecated-copy]
# /jenkins/mjansa/build-ros-v3/artifacts/BUILD-webos-eloquent-master.mcf/work/raspberrypi3-webos-linux-gnueabi/ecl-sigslots/1.0.4-1-r0/git/src/examples/../../include/ecl/sigslots/slot.hpp:243:11: error: implicitly-declared 'constexpr ecl::Slot<ecl::Void>& ecl::Slot<ecl::Void>::operator=(const ecl::Slot<ecl::Void>&)' is deprecated [-Werror=deprecated-copy]

CXXFLAGS += "-Wno-error=deprecated-copy"
