# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_kilted
inherit ros_superflore_generated

DESCRIPTION = "Provides an interface to read the sensor output of a SICK safeVisionary sensor in ROS 2"
AUTHOR = "Christian Eichmann <eichmann@fzi.de>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=10;endline=10;md5=82f0323c08605e5b6f343b05213cf7cc"

ROS_CN = "sick_safevisionary_ros2"
ROS_BPN = "sick_safevisionary_driver"

ROS_BUILD_DEPENDS = "\
    boost \
    cv-bridge \
    lifecycle-msgs \
    rclcpp \
    rclcpp-lifecycle \
    sensor-msgs \
    sick-safevisionary-base \
    sick-safevisionary-interfaces \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    boost \
    cv-bridge \
    lifecycle-msgs \
    rclcpp \
    rclcpp-lifecycle \
    sensor-msgs \
    sick-safevisionary-base \
    sick-safevisionary-interfaces \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    ament-index-cpp \
    builtin-interfaces \
    fastcdr \
    gcc-runtime \
    geometry-msgs \
    libstatistics-collector \
    libyaml \
    libyaml-vendor \
    lttng-ust \
    opencv \
    python3-numpy \
    rcl \
    rcl-interfaces \
    rcl-logging-interface \
    rcl-logging-spdlog \
    rcl-yaml-param-parser \
    rcpputils \
    rcutils \
    rmw \
    rmw-implementation \
    rmw-implementation-cmake \
    rosgraph-msgs \
    rosidl-cmake \
    rosidl-core-runtime \
    rosidl-dynamic-typesupport \
    rosidl-generator-py \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-fastrtps-c \
    rosidl-typesupport-fastrtps-cpp \
    rosidl-typesupport-interface \
    rosidl-typesupport-introspection-c \
    rosidl-typesupport-introspection-cpp \
    service-msgs \
    statistics-msgs \
    std-msgs \
    tracetools \
    type-description-interfaces \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-interfaces-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-python-native \
    ament-cmake-ros-core-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-index-python-native \
    ament-package-native \
    cmake-native \
    gcc-runtime-native \
    pkgconfig-native \
    python3-catkin-pkg-native \
    python3-empy-native \
    python3-native \
    python3-setuptools-native \
    rcpputils-native \
    rcutils-native \
    rosidl-cmake-native \
    rosidl-generator-c-native \
    rosidl-generator-cpp-native \
    rosidl-generator-type-description-native \
    rosidl-pycommon-native \
    rosidl-runtime-c-native \
    rosidl-runtime-cpp-native \
    rosidl-typesupport-c-native \
    rosidl-typesupport-interface-native \
"

ROS_EXEC_DEPENDS = "\
    cv-bridge \
    lifecycle-msgs \
    rclcpp \
    rclcpp-lifecycle \
    sensor-msgs \
    sick-safevisionary-base \
    sick-safevisionary-interfaces \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/sick_safevisionary_ros2-release/archive/release/kilted/sick_safevisionary_driver/1.0.5-1.tar.gz
ROS_BRANCH ?= "branch=release/kilted/sick_safevisionary_driver"
SRC_URI = "git://github.com/ros2-gbp/sick_safevisionary_ros2-release;${ROS_BRANCH};protocol=https"
SRCREV = "85ce3279b73e3339f2962303cbd40bffec3ba808"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
