# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "Wrapper around PyKDL, providing nothing but a dependency on PyKDL on some systems.     On others, it fetches and builds python_orocos_kdl locally."
AUTHOR = "Jacob Perron <jacob@openrobotics.org>"
HOMEPAGE = "https://github.com/orocos/orocos_kinematics_dynamics"
SECTION = "devel"
# Original license in package.xml, joined with "AND" when multiple license tags were used:
#         "Apache License 2.0 AND LGPL-2.1-or-later"
LICENSE = "Apache-2.0 AND LGPL-2.1-or-later"
LIC_FILES_CHKSUM = "file://package.xml;beginline=13;endline=13;md5=f12ef8c0445c08084ae92cf2dcb7ee92"

ROS_CN = "orocos_kdl_vendor"
ROS_BPN = "python_orocos_kdl_vendor"

ROS_BUILD_DEPENDS = "\
    orocos-kdl-vendor \
    pybind11-vendor \
    python3-pykdl \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
    ament-cmake-python-native \
    python-cmake-module-native \
"

ROS_EXPORT_DEPENDS = "\
    orocos-kdl-vendor \
    pybind11-vendor \
    python3-pykdl \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    eigen3-cmake-module \
    libeigen \
    orocos-kdl \
    python3-pybind11 \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-interfaces-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-package-native \
    cmake-native \
    python3-catkin-pkg-native \
    python3-importlib-metadata-native \
    python3-native \
    python3-setuptools-native \
"

ROS_EXEC_DEPENDS = "\
    orocos-kdl-vendor \
    pybind11-vendor \
    python3-pykdl \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-lint-auto \
    ament-lint-common \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/orocos_kdl_vendor-release/archive/release/humble/python_orocos_kdl_vendor/0.2.5-1.tar.gz
ROS_BRANCH ?= "branch=release/humble/python_orocos_kdl_vendor"
SRC_URI = "git://github.com/ros2-gbp/orocos_kdl_vendor-release;${ROS_BRANCH};protocol=https"
SRCREV = "8cd99798448ebd98447a35af86b1626abe7813d8"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
