# Generated by superflore -- DO NOT EDIT
#
# Copyright 2019 Open Source Robotics Foundation

inherit ros_distro_${ROS_DISTRO}
inherit ros_superflore_generated

DESCRIPTION = "Generic Mechanism Controller Library"
AUTHOR = "ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com>"
ROS_AUTHOR = "John Hsu"
HOMEPAGE = "http://ros.org/wiki/robot_mechanism_controllers"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=7;endline=7;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "pr2_controllers"
ROS_BPN = "robot_mechanism_controllers"

ROS_BUILD_DEPENDS = " \
    ${ROS_UNRESOLVED_PLATFORM_PKG_libtool} \
    actionlib \
    angles \
    control-msgs \
    control-toolbox \
    diagnostic-msgs \
    eigen-conversions \
    filters \
    geometry-msgs \
    kdl-parser \
    message-filters \
    message-generation \
    pluginlib \
    pr2-controller-interface \
    pr2-controller-manager \
    pr2-controllers-msgs \
    pr2-mechanism-model \
    realtime-tools \
    roscpp \
    std-msgs \
    tf \
    tf-conversions \
    trajectory-msgs \
"

ROS_BUILDTOOL_DEPENDS = " \
    catkin-native \
"

ROS_EXPORT_DEPENDS = " \
    ${ROS_UNRESOLVED_PLATFORM_PKG_libtool} \
    actionlib \
    angles \
    control-msgs \
    control-toolbox \
    diagnostic-msgs \
    eigen-conversions \
    filters \
    geometry-msgs \
    kdl-parser \
    message-filters \
    message-runtime \
    pluginlib \
    pr2-controller-interface \
    pr2-controller-manager \
    pr2-controllers-msgs \
    pr2-mechanism-model \
    realtime-tools \
    roscpp \
    rospy \
    std-msgs \
    tf \
    tf-conversions \
    trajectory-msgs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    ${ROS_UNRESOLVED_PLATFORM_PKG_libtool} \
    actionlib \
    angles \
    control-msgs \
    control-toolbox \
    diagnostic-msgs \
    eigen-conversions \
    filters \
    geometry-msgs \
    kdl-parser \
    message-filters \
    message-runtime \
    pluginlib \
    pr2-controller-interface \
    pr2-controller-manager \
    pr2-controllers-msgs \
    pr2-mechanism-model \
    realtime-tools \
    roscpp \
    rospy \
    std-msgs \
    tf \
    tf-conversions \
    trajectory-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS_${PN} += "${ROS_EXEC_DEPENDS}"

SRC_URI = "https://github.com/pr2-gbp/pr2_controllers-release/archive/release/melodic/robot_mechanism_controllers/1.10.17-1.tar.gz;downloadfilename=${ROS_SP}.tar.gz"
SRC_URI[md5sum] = "ecf050fa2f53840c79a01973cca5aae2"
SRC_URI[sha256sum] = "9872fd46f89691f6d95342683735e9963d8f170889c5ccc2f2e9a01d437e3800"
S = "${WORKDIR}/pr2_controllers-release-release-melodic-robot_mechanism_controllers-1.10.17-1"

ROS_COMPONENT_TYPE = "${@ros_distro__get_component_type('pr2-controllers', d)}"
ROS_BUILD_TYPE = "catkin"

# Allow the above settings to be overridden.
ROS_INCLUDES_TREE := "${@ros_superflore_generated__get_includes_tree('pr2-controllers', d)}"
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/pr2-controllers/pr2-controllers_common.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/pr2-controllers/pr2-controllers-${PV}_common.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/pr2-controllers/${BPN}.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/pr2-controllers/${BPN}-${PV}.inc

inherit ${ROS_COMPONENT_TYPE}_component
inherit ros_${ROS_BUILD_TYPE}
