# Copyright (c) 2021 LG Electronics, Inc.

# ERROR: lua-vendor-0.0.1-2-r0 do_package: QA Issue: lua-vendor: Files/directories were installed but not shipped in any package:
#   /usr/tmp
#   /usr/tmp/lua-ext-cfgcmd.txt
#   /usr/tmp/lua-ext-cfgcmd.txt.in
#   /usr/src/lua-5.3.2.tar.gz
#   /usr/src/lua-ext
#   /usr/src/lua-ext-build
#   /usr/src/lua-ext-stamp
#   /usr/src/lua-ext/Makefile
#   /usr/src/lua-ext/README
#   /usr/src/lua-ext/CMakeLists.txt
#   /usr/src/lua-ext/src
#   /usr/src/lua-ext/doc
#   /usr/src/lua-ext/src/lualib.h
#   /usr/src/lua-ext/src/liolib.c
#   /usr/src/lua-ext/src/lopcodes.c
#   /usr/src/lua-ext/src/lvm.h
#   /usr/src/lua-ext/src/lauxlib.h
#   /usr/src/lua-ext/src/lobject.h
#   /usr/src/lua-ext/src/lua.hpp
#   /usr/src/lua-ext/src/lgc.h
#   /usr/src/lua-ext/src/lprefix.h
#   /usr/src/lua-ext/src/llex.h
#   /usr/src/lua-ext/src/ltablib.c
#   /usr/src/lua-ext/src/ldebug.h
#   /usr/src/lua-ext/src/Makefile
#   /usr/src/lua-ext/src/ldo.c
#   /usr/src/lua-ext/src/lcode.c
#   /usr/src/lua-ext/src/lzio.h
#   /usr/src/lua-ext/src/ldo.h
#   /usr/src/lua-ext/src/lobject.c
#   /usr/src/lua-ext/src/lmem.h
#   /usr/src/lua-ext/src/ltm.c
#   /usr/src/lua-ext/src/ltm.h
#   /usr/src/lua-ext/src/lstate.h
#   /usr/src/lua-ext/src/lcorolib.c
#   /usr/src/lua-ext/src/lfunc.h
#   /usr/src/lua-ext/src/lzio.c
#   /usr/src/lua-ext/src/lcode.h
#   /usr/src/lua-ext/src/lstate.c
#   /usr/src/lua-ext/src/llimits.h
#   /usr/src/lua-ext/src/lparser.c
#   /usr/src/lua-ext/src/ldblib.c
#   /usr/src/lua-ext/src/lctype.h
#   /usr/src/lua-ext/src/lauxlib.c
#   /usr/src/lua-ext/src/loslib.c
#   /usr/src/lua-ext/src/lstring.c
#   /usr/src/lua-ext/src/lvm.c
#   /usr/src/lua-ext/src/lparser.h
#   /usr/src/lua-ext/src/luac.c
#   /usr/src/lua-ext/src/lapi.h
#   /usr/src/lua-ext/src/lua.h
#   /usr/src/lua-ext/src/lbitlib.c
#   /usr/src/lua-ext/src/lctype.c
#   /usr/src/lua-ext/src/lopcodes.h
#   /usr/src/lua-ext/src/lstring.h
#   /usr/src/lua-ext/src/lgc.c
#   /usr/src/lua-ext/src/lundump.h
#   /usr/src/lua-ext/src/llex.c
#   /usr/src/lua-ext/src/lmem.c
#   /usr/src/lua-ext/src/lutf8lib.c
#   /usr/src/lua-ext/src/ldebug.c
#   /usr/src/lua-ext/src/lfunc.c
#   /usr/src/lua-ext/src/linit.c
#   /usr/src/lua-ext/src/ldump.c
#   /usr/src/lua-ext/src/lstrlib.c
#   /usr/src/lua-ext/src/luaconf.h
#   /usr/src/lua-ext/src/loadlib.c
#   /usr/src/lua-ext/src/ltable.c
#   /usr/src/lua-ext/src/lbaselib.c
#   /usr/src/lua-ext/src/lundump.c
#   /usr/src/lua-ext/src/lua.c
#   /usr/src/lua-ext/src/ltable.h
#   /usr/src/lua-ext/src/lmathlib.c
#   /usr/src/lua-ext/src/lapi.c
#   /usr/src/lua-ext/doc/manual.css
#   /usr/src/lua-ext/doc/manual.html
#   /usr/src/lua-ext/doc/lua.css
#   /usr/src/lua-ext/doc/osi-certified-72x60.png
#   /usr/src/lua-ext/doc/lua.1
#   /usr/src/lua-ext/doc/contents.html
#   /usr/src/lua-ext/doc/logo.gif
#   /usr/src/lua-ext/doc/readme.html
#   /usr/src/lua-ext/doc/luac.1
#   /usr/src/lua-ext/doc/index.css
#   /usr/src/lua-ext-build/.ninja_log
#   /usr/src/lua-ext-build/install_manifest.txt
#   /usr/src/lua-ext-build/.ninja_deps
#   /usr/src/lua-ext-build/cmake_install.cmake
#   /usr/src/lua-ext-build/build.ninja
#   /usr/src/lua-ext-build/liblua_vendor.a
#   /usr/src/lua-ext-build/CMakeCache.txt
#   /usr/src/lua-ext-build/CMakeFiles
#   /usr/src/lua-ext-build/CMakeFiles/TargetDirectories.txt
#   /usr/src/lua-ext-build/CMakeFiles/CMakeOutput.log
#   /usr/src/lua-ext-build/CMakeFiles/rules.ninja
#   /usr/src/lua-ext-build/CMakeFiles/cmake.check_cache
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1
#   /usr/src/lua-ext-build/CMakeFiles/CMakeTmp
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lauxlib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lvm.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/ltable.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/ldo.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lparser.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lbaselib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/liolib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lbitlib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lgc.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lmathlib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/llex.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/ltm.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lzio.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lapi.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lmem.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lstring.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/ldebug.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/loadlib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/ldblib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/linit.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lutf8lib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lfunc.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lstate.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lobject.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/ltablib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lstrlib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lcode.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lopcodes.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/ldump.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lcorolib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/loslib.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lundump.c.o
#   /usr/src/lua-ext-build/CMakeFiles/lua_vendor.dir/src/lctype.c.o
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CMakeSystem.cmake
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CMakeDetermineCompilerABI_CXX.bin
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CMakeDetermineCompilerABI_C.bin
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CMakeCXXCompiler.cmake
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CMakeCCompiler.cmake
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CompilerIdCXX
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CompilerIdC
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CompilerIdCXX/a.out
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CompilerIdCXX/CMakeCXXCompilerId.cpp
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CompilerIdCXX/tmp
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CompilerIdC/CMakeCCompilerId.c
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CompilerIdC/a.out
#   /usr/src/lua-ext-build/CMakeFiles/3.21.1/CompilerIdC/tmp
#   /usr/src/lua-ext-stamp/lua-ext-mkdir
#   /usr/src/lua-ext-stamp/lua-ext-patch
#   /usr/src/lua-ext-stamp/lua-ext-build
#   /usr/src/lua-ext-stamp/lua-ext-done
#   /usr/src/lua-ext-stamp/download-lua-ext.cmake
#   /usr/src/lua-ext-stamp/verify-lua-ext.cmake
#   /usr/src/lua-ext-stamp/lua-ext-urlinfo.txt
#   /usr/src/lua-ext-stamp/extract-lua-ext.cmake
#   /usr/src/lua-ext-stamp/lua-ext-download
#   /usr/src/lua-ext-stamp/lua-ext-install
#   /usr/src/lua-ext-stamp/lua-ext-update
#   /usr/src/lua-ext-stamp/lua-ext-configure
# Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
# lua-vendor: 158 installed and not shipped files. [installed-vs-shipped]
do_install:append() {
    rm -rfv ${D}${prefix}/src ${D}${prefix}/tmp
}

FILESEXTRAPATHS:prepend := "${THISDIR}/${BPN}:"
SRC_URI += "http://www.lua.org/ftp/lua-5.3.2.tar.gz;name=lua;subdir=git/lua-upstream \
    file://0001-lua-fetch-with-bitbake-fetcher-instead-of-ExternalPr.patch \
"
SRC_URI[lua.sha256sum] = "c740c7bb23a936944e1cc63b7c3c5351a8976d7867c5252c8854f7b2af9da68f"
