# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "An open source camera stack and framework for Linux, Android, and ChromeOS"
AUTHOR = "Christian Rauch <Rauch.Christian@gmx.de>"
ROS_AUTHOR = "libcamera project <libcamera-devel@lists.libcamera.org>"
HOMEPAGE = "https://libcamera.org"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "LGPL-2.1"
LICENSE = "LGPL-2.1-only"
LIC_FILES_CHKSUM = "file://package.xml;beginline=12;endline=12;md5=184dd1523b9a109aead3fbbe0b4262e0"

ROS_CN = "libcamera"
ROS_BPN = "libcamera"

ROS_BUILD_DEPENDS = " \
    ${ROS_UNRESOLVED_DEP-python3-ply} \
    gcc-runtime \
    libyaml \
    openssl \
    pkgconfig \
    python3-jinja2 \
    python3-pyyaml \
    udev \
"

ROS_BUILDTOOL_DEPENDS = " \
    ${ROS_UNRESOLVED_DEP-meson-native} \
"

ROS_EXPORT_DEPENDS = " \
    gcc-runtime \
    libyaml \
    openssl \
    udev \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    gcc-runtime \
    libyaml \
    openssl \
    udev \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/libcamera-release/archive/release/humble/libcamera/0.1.0-1.tar.gz
ROS_BRANCH ?= "branch=release/humble/libcamera"
SRC_URI = "git://github.com/ros2-gbp/libcamera-release;${ROS_BRANCH};protocol=https"
SRCREV = "78abec9fda1fc411ab979ab573f69e47a534e07d"
S = "${WORKDIR}/git"

ROS_BUILD_TYPE = "meson"

inherit ros_${ROS_BUILD_TYPE}
