# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_lyrical
inherit ros_superflore_generated

DESCRIPTION = "Interfaces used by py_trees_ros and py_trees_ros_tutorials."
AUTHOR = "Daniel Stonier <d.stonier@gmail.com>"
ROS_AUTHOR = "Daniel Stonier"
HOMEPAGE = "http://ros.org/wiki/py_trees_ros_interfaces"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=13;endline=13;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "py_trees_ros_interfaces"
ROS_BPN = "py_trees_ros_interfaces"

ROS_BUILD_DEPENDS = "\
    action-msgs \
    diagnostic-msgs \
    geometry-msgs \
    rosidl-default-generators \
    unique-identifier-msgs \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    action-msgs \
    diagnostic-msgs \
    geometry-msgs \
    unique-identifier-msgs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    builtin-interfaces \
    fastcdr \
    gcc-runtime \
    rcpputils \
    rcutils \
    rmw \
    rosidl-buffer \
    rosidl-buffer-backend \
    rosidl-buffer-py \
    rosidl-cmake \
    rosidl-core-runtime \
    rosidl-dynamic-typesupport \
    rosidl-generator-py \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-fastrtps-c \
    rosidl-typesupport-fastrtps-cpp \
    rosidl-typesupport-interface \
    rosidl-typesupport-introspection-c \
    rosidl-typesupport-introspection-cpp \
    service-msgs \
    std-msgs \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    action-msgs-native \
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-python-native \
    ament-cmake-ros-core-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-index-python-native \
    ament-package-native \
    builtin-interfaces-native \
    cmake-native \
    fastcdr-native \
    gcc-runtime-native \
    python3-catkin-pkg-native \
    python3-empy-native \
    python3-native \
    python3-setuptools-native \
    rcpputils-native \
    rcutils-native \
    rmw-native \
    ros-environment-native \
    rosidl-buffer-backend-native \
    rosidl-buffer-native \
    rosidl-buffer-py-native \
    rosidl-cmake-native \
    rosidl-core-generators-native \
    rosidl-core-runtime-native \
    rosidl-dynamic-typesupport-native \
    rosidl-generator-c-native \
    rosidl-generator-cpp-native \
    rosidl-generator-py-native \
    rosidl-generator-rs-native \
    rosidl-generator-type-description-native \
    rosidl-pycommon-native \
    rosidl-runtime-c-native \
    rosidl-runtime-cpp-native \
    rosidl-typesupport-c-native \
    rosidl-typesupport-cpp-native \
    rosidl-typesupport-fastrtps-c-native \
    rosidl-typesupport-fastrtps-cpp-native \
    rosidl-typesupport-interface-native \
    rosidl-typesupport-introspection-c-native \
    rosidl-typesupport-introspection-cpp-native \
    service-msgs-native \
    unique-identifier-msgs-native \
"

ROS_EXEC_DEPENDS = "\
    action-msgs \
    diagnostic-msgs \
    geometry-msgs \
    rosidl-default-runtime \
    unique-identifier-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-lint-common \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/py_trees_ros_interfaces-release/archive/release/lyrical/py_trees_ros_interfaces/2.1.2-1.tar.gz
ROS_BRANCH ?= "branch=release/lyrical/py_trees_ros_interfaces"
SRC_URI = "git://github.com/ros2-gbp/py_trees_ros_interfaces-release;${ROS_BRANCH};protocol=https"
SRCREV = "eb33365f5b0dae6191dbddf837dc65763240a4bf"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
