# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_noetic
inherit ros_superflore_generated

DESCRIPTION = "Package to parse NMEA strings and publish a very simple GPS message. Does not     require or use the GPSD deamon."
AUTHOR = "Ed Venator <evenator@gmail.com>"
ROS_AUTHOR = "Eric Perko <eric@ericperko.com>"
HOMEPAGE = "http://ros.org/wiki/nmea_navsat_driver"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=12;endline=12;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "nmea_navsat_driver"
ROS_BPN = "nmea_navsat_driver"

ROS_BUILD_DEPENDS = " \
    python3-catkin-pkg \
"

ROS_BUILDTOOL_DEPENDS = " \
    catkin-native \
"

ROS_EXPORT_DEPENDS = ""

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    geometry-msgs \
    nmea-msgs \
    python3-pyserial \
    rospy \
    sensor-msgs \
    tf \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = " \
    roslint \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros-drivers-gbp/nmea_navsat_driver-release/archive/release/noetic/nmea_navsat_driver/0.6.1-2.tar.gz
ROS_BRANCH ?= "branch=release/noetic/nmea_navsat_driver"
SRC_URI = "git://github.com/ros-drivers-gbp/nmea_navsat_driver-release;${ROS_BRANCH};protocol=https"
SRCREV = "bb80302498b0420b23630c5bf591b12beb2caf04"
S = "${WORKDIR}/git"

ROS_BUILD_TYPE = "catkin"

inherit ros_${ROS_BUILD_TYPE}
