# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_lyrical
inherit ros_superflore_generated

DESCRIPTION = "CMake to generate ROS parameter library."
AUTHOR = "bmagyar <bence.magyar.robotics@gmail.com>"
ROS_AUTHOR = "Paul Gesel <paul.gesel@picknik.ai>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://package.xml;beginline=12;endline=12;md5=4633480cdd27d7906aaf3ef4b72014b2"

ROS_CN = "generate_parameter_library"
ROS_BPN = "generate_parameter_library"

ROS_BUILD_DEPENDS = " \
    ${ROS_UNRESOLVED_DEP-libexpected-dev} \
    fmt \
    rclcpp \
    rclcpp-lifecycle \
    rclpy \
    rsl \
    tcb-span \
"

ROS_BUILDTOOL_DEPENDS = " \
    ament-cmake-native \
    ament-cmake-python-native \
"

ROS_EXPORT_DEPENDS = " \
    ${ROS_UNRESOLVED_DEP-libexpected-dev} \
    fmt \
    rclcpp \
    rclcpp-lifecycle \
    rclpy \
    rsl \
    tcb-span \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = " \
    generate-parameter-library-py-native \
"

ROS_EXEC_DEPENDS = " \
    ${ROS_UNRESOLVED_DEP-libexpected-dev} \
    fmt \
    rclcpp \
    rclcpp-lifecycle \
    rclpy \
    rsl \
    tcb-span \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/generate_parameter_library-release/archive/release/lyrical/generate_parameter_library/1.1.0-1.tar.gz
ROS_BRANCH ?= "branch=release/lyrical/generate_parameter_library"
SRC_URI = "git://github.com/ros2-gbp/generate_parameter_library-release;${ROS_BRANCH};protocol=https"
SRCREV = "69c6fc6da30599ef3b823b54a65935f2fda6b520"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
