# Imported as-is from
# https://github.com/labgrid-project/meta-labgrid/commit/7b3b31b953d954d88f6cde4cd95e1efd6e53b1a3

DESCRIPTION = "An implementation of RFC 7049 - Concise Binary Object Representation (CBOR)."
HOMEPAGE = "https://bitbucket.org/bodhisnarkva/cbor"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/Apache-2.0;md5=89aea4e17d99a7cacdbeed46a0096b10"

inherit pypi
