# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_lyrical
inherit ros_superflore_generated

DESCRIPTION = "The mbf_abstract_nav package contains the abstract navigation server implementation of Move Base Flex (MBF). The abstract navigation server is not bound to any map representation. It provides the actions for planning, controlling and recovering. MBF loads all defined plugins at the program start. Therefor, it loads all plugins which are defined in the lists *planners*, *controllers* and *recovery_behaviors*. Each list holds a pair of a *name* and a *type*. The *type* defines which kind of plugin to load. The *name* defines under which name the plugin should be callable by the actions."
AUTHOR = "Alexander Mock <alexander.mock@naturerobots.com>"
ROS_AUTHOR = "Sebastian Pütz <sebastian.puetz@naturerobots.com>"
HOMEPAGE = "http://github.com/naturerobots/move_base_flex"
SECTION = "devel"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://package.xml;beginline=12;endline=12;md5=4633480cdd27d7906aaf3ef4b72014b2"

ROS_CN = "move_base_flex"
ROS_BPN = "mbf_abstract_nav"

ROS_BUILD_DEPENDS = "\
    geometry-msgs \
    mbf-abstract-core \
    mbf-msgs \
    mbf-utility \
    nav-msgs \
    rclcpp \
    rclcpp-action \
    std-msgs \
    std-srvs \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    geometry-msgs \
    mbf-abstract-core \
    mbf-msgs \
    mbf-utility \
    nav-msgs \
    rclcpp \
    rclcpp-action \
    std-msgs \
    std-srvs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    action-msgs \
    ament-index-cpp \
    builtin-interfaces \
    class-loader \
    composition-interfaces \
    fastcdr \
    gcc-runtime \
    libstatistics-collector \
    libyaml \
    libyaml-vendor \
    lttng-ust \
    message-filters \
    orocos-kdl \
    rcl \
    rcl-action \
    rcl-interfaces \
    rcl-logging-implementation \
    rcl-logging-interface \
    rcl-logging-spdlog \
    rcl-yaml-param-parser \
    rclcpp-components \
    rcpputils \
    rcutils \
    rmw \
    rmw-implementation \
    rmw-implementation-cmake \
    rosgraph-msgs \
    rosidl-buffer \
    rosidl-buffer-backend \
    rosidl-buffer-py \
    rosidl-cmake \
    rosidl-core-runtime \
    rosidl-dynamic-typesupport \
    rosidl-generator-py \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-fastrtps-c \
    rosidl-typesupport-fastrtps-cpp \
    rosidl-typesupport-interface \
    rosidl-typesupport-introspection-c \
    rosidl-typesupport-introspection-cpp \
    service-msgs \
    statistics-msgs \
    tf2 \
    tf2-geometry-msgs \
    tf2-msgs \
    tf2-ros \
    tracetools \
    type-description-interfaces \
    unique-identifier-msgs \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-python-native \
    ament-cmake-ros-core-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-index-python-native \
    ament-package-native \
    cmake-native \
    gcc-runtime-native \
    pkgconfig-native \
    python3-catkin-pkg-native \
    python3-empy-native \
    python3-native \
    python3-setuptools-native \
    rcpputils-native \
    rcutils-native \
    rosidl-buffer-native \
    rosidl-cmake-native \
    rosidl-generator-c-native \
    rosidl-generator-cpp-native \
    rosidl-generator-type-description-native \
    rosidl-pycommon-native \
    rosidl-runtime-c-native \
    rosidl-runtime-cpp-native \
    rosidl-typesupport-c-native \
    rosidl-typesupport-interface-native \
"

ROS_EXEC_DEPENDS = "\
    geometry-msgs \
    mbf-abstract-core \
    mbf-msgs \
    mbf-utility \
    nav-msgs \
    rclcpp \
    rclcpp-action \
    std-msgs \
    std-srvs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-cmake-gmock \
    ament-cmake-gtest \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/move_base_flex-release/archive/release/lyrical/mbf_abstract_nav/1.2.1-1.tar.gz
ROS_BRANCH ?= "branch=release/lyrical/mbf_abstract_nav"
SRC_URI = "git://github.com/ros2-gbp/move_base_flex-release;${ROS_BRANCH};protocol=https"
SRCREV = "262f901db9899274d18f67a642f3106202f18eb7"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
