# Generated by superflore -- DO NOT EDIT
#
# Copyright 2019 Open Source Robotics Foundation

inherit ros_distro_${ROS_DISTRO}
inherit ros_superflore_generated

DESCRIPTION = "Track the output of the leg_detector to indicate the velocity of person."
AUTHOR = "David V. Lu!! <davidvlu@gmail.com>"
ROS_AUTHOR = "David V. Lu!! <davidvlu@gmail.com>"
HOMEPAGE = "http://ros.org/wiki/people_velocity_tracker"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=7;endline=7;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "people"
ROS_BPN = "people_velocity_tracker"

ROS_BUILD_DEPENDS = " \
    easy-markers \
    geometry-msgs \
    kalman-filter \
    people-msgs \
    roslib \
    rospy \
"

ROS_BUILDTOOL_DEPENDS = " \
    catkin-native \
"

ROS_EXPORT_DEPENDS = " \
    easy-markers \
    geometry-msgs \
    kalman-filter \
    people-msgs \
    roslib \
    rospy \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    easy-markers \
    geometry-msgs \
    kalman-filter \
    leg-detector \
    people-msgs \
    roslib \
    rospy \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS_${PN} += "${ROS_EXEC_DEPENDS}"

SRC_URI = "https://github.com/OSUrobotics/people-release/archive/release/kinetic/people_velocity_tracker/1.1.3-1.tar.gz;downloadfilename=${ROS_SP}.tar.gz"
SRC_URI[md5sum] = "e7f966bb0620e1a3be19d26fb2a6486b"
SRC_URI[sha256sum] = "24595ad999e124490d6648ef5732faa5518d4a45dabe4e58da8a6348cce95bbc"
S = "${WORKDIR}/people-release-release-kinetic-people_velocity_tracker-1.1.3-1"

ROS_COMPONENT_TYPE = "${@ros_distro__get_component_type('people', d)}"
ROS_BUILD_TYPE = "catkin"

# Allow the above settings to be overridden.
ROS_INCLUDES_TREE := "${@ros_superflore_generated__get_includes_tree('people', d)}"
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/people/people_common.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/people/people-${PV}_common.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/people/${BPN}.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/people/${BPN}-${PV}.inc

inherit ${ROS_COMPONENT_TYPE}_component
inherit ros_${ROS_BUILD_TYPE}
