# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_lyrical
inherit ros_superflore_generated

DESCRIPTION = "Contains URDF and meshes to create models of Stereolabs ZED Cameras."
AUTHOR = "STEREOLABS <support@stereolabs.com>"
HOMEPAGE = "https://www.stereolabs.com/"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "Apache License 2.0"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=12;endline=12;md5=12c26a18c7f493fdc7e8a93b16b7c04f"

ROS_CN = "zed-ros2-description"
ROS_BPN = "zed_description"

ROS_BUILD_DEPENDS = "\
    ament-cmake-auto \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = ""

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = ""

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-libgtest-dev-native} \
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-gmock-native \
    ament-cmake-gtest-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-python-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-package-native \
    cmake-native \
    gtest-native \
    python3-catkin-pkg-native \
    python3-setuptools-native \
"

ROS_EXEC_DEPENDS = "\
    rviz2 \
    xacro \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-cmake-copyright \
    ament-cmake-cppcheck \
    ament-cmake-lint-cmake \
    ament-cmake-pep257 \
    ament-cmake-uncrustify \
    ament-cmake-xmllint \
    ament-lint-auto \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/zed-ros2-description-release/archive/release/lyrical/zed_description/0.1.5-1.tar.gz
ROS_BRANCH ?= "branch=release/lyrical/zed_description"
SRC_URI = "git://github.com/ros2-gbp/zed-ros2-description-release;${ROS_BRANCH};protocol=https"
SRCREV = "aed89bdf9dedd7630d6564d9e3bdfd9a2bfd6ac6"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
