# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_kilted
inherit ros_superflore_generated

DESCRIPTION = "ROS 2 package providing a hardware interface for controlling Dynamixel motors via the ROS 2 control framework."
AUTHOR = "Pyo <pyo@robotis.com>"
ROS_AUTHOR = "Hye-Jong KIM <hjkim@robotis.com>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "Apache 2.0"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=10;endline=10;md5=3dce4ba60d7e51ec64f3c3dc18672dd3"

ROS_CN = "dynamixel_hardware_interface"
ROS_BPN = "dynamixel_hardware_interface"

ROS_BUILD_DEPENDS = " \
    dynamixel-interfaces \
    dynamixel-sdk \
    hardware-interface \
    pluginlib \
    rclcpp \
    realtime-tools \
    std-srvs \
"

ROS_BUILDTOOL_DEPENDS = " \
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = " \
    dynamixel-interfaces \
    dynamixel-sdk \
    hardware-interface \
    pluginlib \
    rclcpp \
    realtime-tools \
    std-srvs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    dynamixel-interfaces \
    dynamixel-sdk \
    hardware-interface \
    pluginlib \
    rclcpp \
    realtime-tools \
    std-srvs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = " \
    ament-lint-auto \
    ament-lint-common \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/dynamixel_hardware_interface-release/archive/release/kilted/dynamixel_hardware_interface/1.4.15-1.tar.gz
ROS_BRANCH ?= "branch=release/kilted/dynamixel_hardware_interface"
SRC_URI = "git://github.com/ros2-gbp/dynamixel_hardware_interface-release;${ROS_BRANCH};protocol=https"
SRCREV = "249d24531491ec20d2be5b200f76fcd4c9007d3b"
S = "${WORKDIR}/git"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
