# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_lyrical
inherit ros_superflore_generated

DESCRIPTION = "Converts a 3D Point Cloud into a 2D laser scan. This is useful for making devices like the Kinect appear like a laser scanner for 2D-based algorithms (e.g. laser-based SLAM)."
AUTHOR = "Paul Bovbel <paul@bovbel.com>"
ROS_AUTHOR = "Paul Bovbel <paul@bovbel.com>"
HOMEPAGE = "http://ros.org/wiki/perception_pcl"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=13;endline=13;md5=01c2bc31767ccb3a68e12f02612b2a97"

ROS_CN = "pointcloud_to_laserscan"
ROS_BPN = "pointcloud_to_laserscan"

ROS_BUILD_DEPENDS = "\
    laser-geometry \
    message-filters \
    rclcpp \
    rclcpp-components \
    sensor-msgs \
    tf2 \
    tf2-ros \
    tf2-sensor-msgs \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    laser-geometry \
    message-filters \
    rclcpp \
    rclcpp-components \
    sensor-msgs \
    tf2 \
    tf2-ros \
    tf2-sensor-msgs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    action-msgs \
    ament-index-cpp \
    builtin-interfaces \
    class-loader \
    composition-interfaces \
    fastcdr \
    geometry-msgs \
    libeigen \
    libstatistics-collector \
    libyaml \
    libyaml-vendor \
    lttng-ust \
    rcl \
    rcl-action \
    rcl-interfaces \
    rcl-logging-implementation \
    rcl-logging-interface \
    rcl-logging-spdlog \
    rcl-yaml-param-parser \
    rclcpp-action \
    rcpputils \
    rcutils \
    rmw \
    rmw-implementation \
    rmw-implementation-cmake \
    rosgraph-msgs \
    rosidl-buffer \
    rosidl-buffer-backend \
    rosidl-buffer-py \
    rosidl-cmake \
    rosidl-core-runtime \
    rosidl-dynamic-typesupport \
    rosidl-generator-py \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-fastrtps-c \
    rosidl-typesupport-fastrtps-cpp \
    rosidl-typesupport-interface \
    rosidl-typesupport-introspection-c \
    rosidl-typesupport-introspection-cpp \
    service-msgs \
    statistics-msgs \
    std-msgs \
    tf2-msgs \
    tracetools \
    type-description-interfaces \
    unique-identifier-msgs \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-python-native \
    ament-cmake-ros-core-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-index-python-native \
    ament-package-native \
    cmake-native \
    eigen3-cmake-module-native \
    pkgconfig-native \
    python3-catkin-pkg-native \
    python3-empy-native \
    python3-native \
    python3-setuptools-native \
    rcpputils-native \
    rcutils-native \
    rosidl-buffer-native \
    rosidl-cmake-native \
    rosidl-generator-c-native \
    rosidl-generator-cpp-native \
    rosidl-generator-type-description-native \
    rosidl-pycommon-native \
    rosidl-runtime-c-native \
    rosidl-runtime-cpp-native \
    rosidl-typesupport-c-native \
    rosidl-typesupport-interface-native \
"

ROS_EXEC_DEPENDS = "\
    laser-geometry \
    launch \
    launch-ros \
    message-filters \
    rclcpp \
    rclcpp-components \
    sensor-msgs \
    tf2 \
    tf2-ros \
    tf2-sensor-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-cmake-cppcheck \
    ament-cmake-cpplint \
    ament-cmake-flake8 \
    ament-cmake-lint-cmake \
    ament-cmake-pep257 \
    ament-cmake-uncrustify \
    ament-cmake-xmllint \
    ament-lint-auto \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/pointcloud_to_laserscan-release/archive/release/lyrical/pointcloud_to_laserscan/2.1.0-3.tar.gz
ROS_BRANCH ?= "branch=release/lyrical/pointcloud_to_laserscan"
SRC_URI = "git://github.com/ros2-gbp/pointcloud_to_laserscan-release;${ROS_BRANCH};protocol=https"
SRCREV = "3e30a200807b70e1933c08d896c0f0c55c9cfd47"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
