# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "Package for turtlebot3 panorama."
AUTHOR = "Pyo <pyo@robotis.com>"
ROS_AUTHOR = "Christopher Tatsch"
HOMEPAGE = "http://turtlebot3.robotis.com"
SECTION = "devel"
LICENSE = "BSD-3-Clause"
LIC_FILES_CHKSUM = "file://package.xml;beginline=10;endline=10;md5=4633480cdd27d7906aaf3ef4b72014b2"

ROS_CN = "turtlebot3_applications"
ROS_BPN = "turtlebot3_panorama"

ROS_BUILD_DEPENDS = "\
    boost \
    cv-bridge \
    geometry-msgs \
    image-transport \
    nav-msgs \
    opencv \
    rclcpp \
    sensor-msgs \
    tf2 \
    tf2-geometry-msgs \
    turtlebot3-applications-msgs \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    boost \
    cv-bridge \
    geometry-msgs \
    image-transport \
    nav-msgs \
    opencv \
    rclcpp \
    sensor-msgs \
    tf2 \
    tf2-geometry-msgs \
    turtlebot3-applications-msgs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    action-msgs \
    ament-cmake \
    ament-cmake-core \
    ament-cmake-export-definitions \
    ament-cmake-export-dependencies \
    ament-cmake-export-include-directories \
    ament-cmake-export-interfaces \
    ament-cmake-export-libraries \
    ament-cmake-export-link-flags \
    ament-cmake-export-targets \
    ament-cmake-gen-version-h \
    ament-cmake-libraries \
    ament-cmake-python \
    ament-cmake-target-dependencies \
    ament-cmake-test \
    ament-cmake-version \
    ament-index-cpp \
    builtin-interfaces \
    class-loader \
    console-bridge \
    console-bridge-vendor \
    eigen3-cmake-module \
    libeigen \
    libstatistics-collector \
    libtinyxml2 \
    libyaml \
    libyaml-vendor \
    message-filters \
    opencv \
    orocos-kdl \
    orocos-kdl-vendor \
    pluginlib \
    python3-numpy \
    rcl \
    rcl-action \
    rcl-interfaces \
    rcl-logging-interface \
    rcl-logging-spdlog \
    rcl-yaml-param-parser \
    rclcpp-action \
    rclcpp-components \
    rcpputils \
    rcutils \
    rmw \
    rmw-implementation \
    rmw-implementation-cmake \
    rosgraph-msgs \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-interface \
    statistics-msgs \
    std-msgs \
    tf2-msgs \
    tf2-ros \
    tinyxml2-vendor \
    tracetools \
    unique-identifier-msgs \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-interfaces-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-python-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-package-native \
    cmake-native \
    python3-catkin-pkg-native \
    python3-importlib-metadata-native \
    python3-native \
    python3-setuptools-native \
"

ROS_EXEC_DEPENDS = "\
    boost \
    cv-bridge \
    geometry-msgs \
    image-transport \
    nav-msgs \
    opencv \
    rclcpp \
    sensor-msgs \
    tf2 \
    tf2-geometry-msgs \
    turtlebot3-applications-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/turtlebot3_applications-release/archive/release/humble/turtlebot3_panorama/1.3.3-2.tar.gz
ROS_BRANCH ?= "branch=release/humble/turtlebot3_panorama"
SRC_URI = "git://github.com/ros2-gbp/turtlebot3_applications-release;${ROS_BRANCH};protocol=https"
SRCREV = "b7994b5861a054775e6e81c12b4d2ccdc8b13c37"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
