# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_melodic
inherit ros_superflore_generated

DESCRIPTION = "The jderobot_color_tuner tool package"
AUTHOR = "Pankhuri Vanjani <pankhurivanjani@gmail.com>"
ROS_AUTHOR = "Pankhuri Vanjani <pankhurivanjani@gmail.com>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "GPLv3"
LICENSE = "GPL-3.0-only"
LIC_FILES_CHKSUM = "file://package.xml;beginline=11;endline=11;md5=1e7b3bcc2e271699c77c769685058cbe"

ROS_CN = "jderobot_color_tuner"
ROS_BPN = "jderobot_color_tuner"

ROS_BUILD_DEPENDS = " \
    ${PYTHON_PN}-rospkg \
    cv-bridge \
    image-transport \
    roslib \
    rospy \
    sensor-msgs \
    std-msgs \
"

ROS_BUILDTOOL_DEPENDS = " \
    catkin-native \
"

ROS_EXPORT_DEPENDS = " \
    ${PYTHON_PN}-rospkg \
    cv-bridge \
    image-transport \
    roslib \
    rospy \
    sensor-msgs \
    std-msgs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    ${PYTHON_PN}-rospkg \
    cv-bridge \
    image-transport \
    roslib \
    rospy \
    sensor-msgs \
    std-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS_${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/JdeRobot/ColorTuner-release/archive/release/melodic/jderobot_color_tuner/0.0.5-2.tar.gz
ROS_BRANCH ?= "branch=release/melodic/jderobot_color_tuner"
SRC_URI = "git://github.com/JdeRobot/ColorTuner-release;${ROS_BRANCH};protocol=https"
SRCREV = "7704c59a57ad1b5ddbc12ae10c6614bd91c77f7d"
S = "${WORKDIR}/git"

ROS_BUILD_TYPE = "catkin"

inherit ros_${ROS_BUILD_TYPE}
