# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "A ROS 2 extension for the cloud deployment of computational graphs in a cloud-provider     agnostic and security-conscious manner."
AUTHOR = "Jeff Ichnowski <jeffi@berkeley.edu>"
ROS_AUTHOR = "Jeff Ichnowski <jeffi@berkeley.edu>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "Apache License 2.0"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=24;endline=24;md5=12c26a18c7f493fdc7e8a93b16b7c04f"

ROS_CN = "fogros2"
ROS_BPN = "fogros2"

ROS_BUILD_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-python3-scp} \
    ${ROS_UNRESOLVED_DEP-wireguard} \
    python3-boto3 \
    python3-paramiko \
    rmw-cyclonedds-cpp \
    ros2cli \
"

ROS_BUILDTOOL_DEPENDS = ""

ROS_EXPORT_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-python3-scp} \
    ${ROS_UNRESOLVED_DEP-wireguard} \
    python3-boto3 \
    python3-paramiko \
    rmw-cyclonedds-cpp \
    ros2cli \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    acl \
    cyclonedds \
    gcc-runtime \
    iceoryx-binding-c \
    iceoryx-hoofs \
    iceoryx-posh \
    rcpputils \
    rcutils \
    rmw \
    rmw-dds-common \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-interface \
    rosidl-typesupport-introspection-c \
    rosidl-typesupport-introspection-cpp \
    tracetools \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-interfaces-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-native \
    ament-cmake-python-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-package-native \
    cmake-native \
    python3-catkin-pkg-native \
    python3-empy-native \
    python3-importlib-metadata-native \
    python3-native \
    python3-setuptools-native \
    rosidl-cmake-native \
"

ROS_EXEC_DEPENDS = "\
    ${ROS_UNRESOLVED_DEP-python3-scp} \
    ${ROS_UNRESOLVED_DEP-wireguard} \
    python3-boto3 \
    python3-paramiko \
    rmw-cyclonedds-cpp \
    ros2cli \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-copyright \
    ament-flake8 \
    ament-pep257 \
    python3-pytest \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/fogros2-release/archive/release/humble/fogros2/0.1.7-1.tar.gz
ROS_BRANCH ?= "branch=release/humble/fogros2"
SRC_URI = "git://github.com/ros2-gbp/fogros2-release;${ROS_BRANCH};protocol=https"
SRCREV = "191da6cc078839f53ac2ee050d0f0aacd8880462"

ROS_BUILD_TYPE = "ament_python"

inherit ros_${ROS_BUILD_TYPE}
