# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_melodic
inherit ros_superflore_generated

DESCRIPTION = "A package to support MongoDB-based storage and analysis for data from a ROS system, eg. saved messages, configurations etc"
AUTHOR = "Nick Hawes <nickh@robots.ox.ac.uk>"
ROS_AUTHOR = "Chris Burbridge"
HOMEPAGE = "http://www.ros.org/wiki/mongodb_store"
SECTION = "devel"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://package.xml;beginline=13;endline=13;md5=58e54c03ca7f821dd3967e2a2cd1596e"

ROS_CN = "mongodb_store"
ROS_BPN = "mongodb_store"

ROS_BUILD_DEPENDS = " \
    ${PYTHON_PN}-catkin-pkg \
    ${ROS_UNRESOLVED_PLATFORM_PKG_libmongoclient-dev} \
    ${ROS_UNRESOLVED_PLATFORM_PKG_mongodb} \
    geometry-msgs \
    message-generation \
    mongodb-store-msgs \
    openssl \
    roscpp \
    rospy \
    rostest \
    std-msgs \
    std-srvs \
    topic-tools \
"

ROS_BUILDTOOL_DEPENDS = " \
    catkin-native \
"

ROS_EXPORT_DEPENDS = " \
    ${PYTHON_PN}-future \
    ${ROS_UNRESOLVED_PLATFORM_PKG_libmongoclient-dev} \
    ${ROS_UNRESOLVED_PLATFORM_PKG_mongodb} \
    ${ROS_UNRESOLVED_PLATFORM_PKG_python-pymongo} \
    geometry-msgs \
    mongodb-store-msgs \
    roscpp \
    rospy \
    std-msgs \
    std-srvs \
    topic-tools \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    ${PYTHON_PN}-future \
    ${ROS_UNRESOLVED_PLATFORM_PKG_libmongoclient-dev} \
    ${ROS_UNRESOLVED_PLATFORM_PKG_mongodb} \
    ${ROS_UNRESOLVED_PLATFORM_PKG_python-pymongo} \
    geometry-msgs \
    mongodb-store-msgs \
    roscpp \
    rospy \
    std-msgs \
    std-srvs \
    topic-tools \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS_${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/strands-project-releases/mongodb_store/archive/release/melodic/mongodb_store/0.5.2-1.tar.gz
ROS_BRANCH ?= "branch=release/melodic/mongodb_store"
SRC_URI = "git://github.com/strands-project-releases/mongodb_store;${ROS_BRANCH};protocol=https"
SRCREV = "39c134ea3c9630b8a50d051a84870ce437bc31eb"
S = "${WORKDIR}/git"

ROS_BUILD_TYPE = "catkin"

inherit ros_${ROS_BUILD_TYPE}
