# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_kilted
inherit ros_superflore_generated

DESCRIPTION = "ROS interface for the grid map library to manage two-dimensional grid maps with multiple data layers."
AUTHOR = "Maximilian Wulf <mwulf@anybotics.com>"
ROS_AUTHOR = "Péter Fankhauser <pfankhauser@anybotics.com>"
HOMEPAGE = "http://github.com/anybotics/grid_map"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=9;endline=9;md5=d566ef916e9dedc494f5f793a6690ba5"

ROS_CN = "grid_map"
ROS_BPN = "grid_map_ros"

ROS_BUILD_DEPENDS = "\
    cv-bridge \
    geometry-msgs \
    grid-map-cmake-helpers \
    grid-map-core \
    grid-map-cv \
    grid-map-msgs \
    nav-msgs \
    nav2-msgs \
    rclcpp \
    rcutils \
    rosbag2-cpp \
    sensor-msgs \
    std-msgs \
    tf2 \
    visualization-msgs \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    cv-bridge \
    geometry-msgs \
    grid-map-core \
    grid-map-cv \
    grid-map-msgs \
    nav-msgs \
    nav2-msgs \
    rclcpp \
    rcutils \
    rosbag2-cpp \
    sensor-msgs \
    std-msgs \
    tf2 \
    visualization-msgs \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    action-msgs \
    ament-index-cpp \
    boost \
    builtin-interfaces \
    class-loader \
    fastcdr \
    filters \
    gcc-runtime \
    geographic-msgs \
    libeigen \
    libstatistics-collector \
    libtinyxml2 \
    libyaml \
    libyaml-vendor \
    lttng-ust \
    opencv \
    pluginlib \
    python3-numpy \
    rcl \
    rcl-interfaces \
    rcl-logging-interface \
    rcl-logging-spdlog \
    rcl-yaml-param-parser \
    rcpputils \
    rmw \
    rmw-implementation \
    rmw-implementation-cmake \
    rosbag2-storage \
    rosgraph-msgs \
    rosidl-cmake \
    rosidl-core-runtime \
    rosidl-default-generators \
    rosidl-dynamic-typesupport \
    rosidl-generator-py \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-fastrtps-c \
    rosidl-typesupport-fastrtps-cpp \
    rosidl-typesupport-interface \
    rosidl-typesupport-introspection-c \
    rosidl-typesupport-introspection-cpp \
    service-msgs \
    statistics-msgs \
    tinyxml2-vendor \
    tracetools \
    type-description-interfaces \
    unique-identifier-msgs \
    yaml-cpp \
    yaml-cpp-vendor \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    action-msgs-native \
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-interfaces-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-python-native \
    ament-cmake-ros-core-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-index-python-native \
    ament-package-native \
    builtin-interfaces-native \
    cmake-native \
    fastcdr-native \
    gcc-runtime-native \
    pkgconfig-native \
    python3-catkin-pkg-native \
    python3-empy-native \
    python3-native \
    python3-setuptools-native \
    rcpputils-native \
    rcutils-native \
    rmw-native \
    ros-environment-native \
    rosidl-cmake-native \
    rosidl-core-generators-native \
    rosidl-core-runtime-native \
    rosidl-dynamic-typesupport-native \
    rosidl-generator-c-native \
    rosidl-generator-cpp-native \
    rosidl-generator-py-native \
    rosidl-generator-rs-native \
    rosidl-generator-type-description-native \
    rosidl-pycommon-native \
    rosidl-runtime-c-native \
    rosidl-runtime-cpp-native \
    rosidl-typesupport-c-native \
    rosidl-typesupport-cpp-native \
    rosidl-typesupport-fastrtps-c-native \
    rosidl-typesupport-fastrtps-cpp-native \
    rosidl-typesupport-interface-native \
    rosidl-typesupport-introspection-c-native \
    rosidl-typesupport-introspection-cpp-native \
    service-msgs-native \
    unique-identifier-msgs-native \
"

ROS_EXEC_DEPENDS = "\
    cv-bridge \
    geometry-msgs \
    grid-map-core \
    grid-map-cv \
    grid-map-msgs \
    nav-msgs \
    nav2-msgs \
    rclcpp \
    rcutils \
    rosbag2-cpp \
    sensor-msgs \
    std-msgs \
    tf2 \
    visualization-msgs \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-cmake-gtest \
    ament-lint-auto \
    ament-lint-common \
    rosbag2-storage-default-plugins \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/grid_map-release/archive/release/kilted/grid_map_ros/2.4.0-1.tar.gz
ROS_BRANCH ?= "branch=release/kilted/grid_map_ros"
SRC_URI = "git://github.com/ros2-gbp/grid_map-release;${ROS_BRANCH};protocol=https"
SRCREV = "4e9c32faa03d1db7ca43b3f77492c05f10a74ddc"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
