# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_rolling
inherit ros_superflore_generated

DESCRIPTION = "TODO: Package description"
AUTHOR = "miguel <mgons@unileon.es>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "TODO: License declaration"
LICENSE = "TODO-License-declaration"
LIC_FILES_CHKSUM = "file://package.xml;beginline=8;endline=8;md5=782925c2d55d09052e1842a0b4886802"

ROS_CN = "yasmin"
ROS_BPN = "yasmin_viewer"

ROS_BUILD_DEPENDS = " \
    rclcpp \
    rclpy \
    yasmin \
    yasmin-msgs \
    yasmin-ros \
"

ROS_BUILDTOOL_DEPENDS = " \
    ament-cmake-native \
    ament-cmake-python-native \
"

ROS_EXPORT_DEPENDS = " \
    rclcpp \
    rclpy \
    yasmin \
    yasmin-msgs \
    yasmin-ros \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    ${ROS_UNRESOLVED_DEP-python3-expiringdict} \
    ${ROS_UNRESOLVED_DEP-python3-waitress} \
    python3-flask \
    rclcpp \
    rclpy \
    yasmin \
    yasmin-msgs \
    yasmin-ros \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = " \
    ament-copyright \
    ament-flake8 \
    ament-pep257 \
    python3-pytest \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/yasmin-release/archive/release/rolling/yasmin_viewer/3.1.0-1.tar.gz
ROS_BRANCH ?= "branch=release/rolling/yasmin_viewer"
SRC_URI = "git://github.com/ros2-gbp/yasmin-release;${ROS_BRANCH};protocol=https"
SRCREV = "95b6767bbb5689afae2ec113dd00bb0bca9c665d"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
