# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "Security extensions for ros2 launch"
AUTHOR = "Ted Kern <ted.kern@canonical.com>"
ROS_AUTHOR = "Geoffrey Biggs <geoff@openrobotics.org>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "Apache License 2.0"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=10;endline=10;md5=12c26a18c7f493fdc7e8a93b16b7c04f"

ROS_CN = "ros2launch_security"
ROS_BPN = "ros2launch_security"

ROS_BUILD_DEPENDS = "\
    ament-index-python \
    nodl-python \
    ros2launch \
    sros2 \
"

ROS_BUILDTOOL_DEPENDS = ""

ROS_EXPORT_DEPENDS = "\
    ament-index-python \
    nodl-python \
    ros2launch \
    sros2 \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    action-msgs \
    ament-index-cpp \
    builtin-interfaces \
    composition-interfaces \
    launch \
    launch-ros \
    libyaml \
    libyaml-vendor \
    lifecycle-msgs \
    osrf-pycommon \
    python3 \
    python3-importlib-metadata \
    python3-lxml \
    python3-pyyaml \
    rcl \
    rcl-action \
    rcl-interfaces \
    rcl-lifecycle \
    rcl-logging-interface \
    rcl-logging-spdlog \
    rcl-yaml-param-parser \
    rclpy \
    rcpputils \
    rcutils \
    rmw \
    rmw-implementation \
    rmw-implementation-cmake \
    ros2cli \
    ros2pkg \
    rosidl-runtime-c \
    rosidl-typesupport-interface \
    tracetools \
    unique-identifier-msgs \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-interfaces-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-native \
    ament-cmake-python-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-package-native \
    cmake-native \
    python3-catkin-pkg-native \
    python3-importlib-metadata-native \
    python3-native \
    python3-setuptools-native \
"

ROS_EXEC_DEPENDS = "\
    ament-index-python \
    nodl-python \
    ros2launch \
    sros2 \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    ament-copyright \
    ament-flake8 \
    ament-pep257 \
    demo-nodes-py \
    launch-ros \
    python3-pytest \
    ros2launch \
    sros2 \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/ros2launch_security-release/archive/release/humble/ros2launch_security/1.0.0-3.tar.gz
ROS_BRANCH ?= "branch=release/humble/ros2launch_security"
SRC_URI = "git://github.com/ros2-gbp/ros2launch_security-release;${ROS_BRANCH};protocol=https"
SRCREV = "0319b727c62bf805b225995defc6b952374d19af"

ROS_BUILD_TYPE = "ament_python"

inherit ros_${ROS_BUILD_TYPE}
