# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "Implementation of simple kinematics in two and half dimensions"
AUTHOR = "David V. Lu!! <davidvlu@gmail.com>"
HOMEPAGE = "https://wiki.ros.org"
SECTION = "devel"
# Original license in package.xml, joined with "&" when multiple license tags were used:
#         "BSD 3-clause"
LICENSE = "BSD-3-clause"
LIC_FILES_CHKSUM = "file://package.xml;beginline=8;endline=8;md5=79773b05553c027a06a89128fefb052f"

ROS_CN = "metro_nav"
ROS_BPN = "base2d_kinematics"

ROS_BUILD_DEPENDS = "\
    base2d-kinematics-msgs \
    geometry-msgs \
    nav-2d-msgs \
    rclcpp \
"

ROS_BUILDTOOL_DEPENDS = "\
    ament-cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    base2d-kinematics-msgs \
    geometry-msgs \
    nav-2d-msgs \
    rclcpp \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    ament-index-cpp \
    builtin-interfaces \
    fastcdr \
    libstatistics-collector \
    libyaml \
    libyaml-vendor \
    rcl \
    rcl-interfaces \
    rcl-logging-interface \
    rcl-logging-spdlog \
    rcl-yaml-param-parser \
    rcpputils \
    rcutils \
    rmw \
    rmw-implementation \
    rmw-implementation-cmake \
    rosgraph-msgs \
    rosidl-cmake \
    rosidl-default-generators \
    rosidl-default-runtime \
    rosidl-generator-py \
    rosidl-runtime-c \
    rosidl-runtime-cpp \
    rosidl-typesupport-c \
    rosidl-typesupport-cpp \
    rosidl-typesupport-fastrtps-c \
    rosidl-typesupport-fastrtps-cpp \
    rosidl-typesupport-interface \
    rosidl-typesupport-introspection-c \
    rosidl-typesupport-introspection-cpp \
    statistics-msgs \
    std-msgs \
    tracetools \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = "\
    ament-cmake-core-native \
    ament-cmake-export-definitions-native \
    ament-cmake-export-dependencies-native \
    ament-cmake-export-include-directories-native \
    ament-cmake-export-interfaces-native \
    ament-cmake-export-libraries-native \
    ament-cmake-export-link-flags-native \
    ament-cmake-export-targets-native \
    ament-cmake-gen-version-h-native \
    ament-cmake-gmock-native \
    ament-cmake-gtest-native \
    ament-cmake-include-directories-native \
    ament-cmake-libraries-native \
    ament-cmake-pytest-native \
    ament-cmake-python-native \
    ament-cmake-ros-native \
    ament-cmake-target-dependencies-native \
    ament-cmake-test-native \
    ament-cmake-version-native \
    ament-index-python-native \
    ament-package-native \
    cmake-native \
    domain-coordinator-native \
    fastcdr-native \
    fastrtps-cmake-module-native \
    gmock-vendor-native \
    gtest-native \
    gtest-vendor-native \
    python-cmake-module-native \
    python3-catkin-pkg-native \
    python3-empy-native \
    python3-importlib-metadata-native \
    python3-native \
    python3-pytest-native \
    python3-setuptools-native \
    rcpputils-native \
    rcutils-native \
    rmw-native \
    ros-environment-native \
    rosidl-cmake-native \
    rosidl-generator-c-native \
    rosidl-generator-cpp-native \
    rosidl-generator-py-native \
    rosidl-generator-rs-native \
    rosidl-runtime-c-native \
    rosidl-runtime-cpp-native \
    rosidl-typesupport-c-native \
    rosidl-typesupport-cpp-native \
    rosidl-typesupport-fastrtps-c-native \
    rosidl-typesupport-fastrtps-cpp-native \
    rosidl-typesupport-interface-native \
    rosidl-typesupport-introspection-c-native \
    rosidl-typesupport-introspection-cpp-native \
"

ROS_EXEC_DEPENDS = "\
    base2d-kinematics-msgs \
    geometry-msgs \
    nav-2d-msgs \
    rclcpp \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/metro_nav-release/archive/release/humble/base2d_kinematics/0.2.0-1.tar.gz
ROS_BRANCH ?= "branch=release/humble/base2d_kinematics"
SRC_URI = "git://github.com/ros2-gbp/metro_nav-release;${ROS_BRANCH};protocol=https"
SRCREV = "596fe0db3224aae00523fd21607a9ea171f5a6b7"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}
