# Generated by superflore -- DO NOT EDIT
#
# Copyright 2019 Open Source Robotics Foundation

inherit ros_distro_${ROS_DISTRO}
inherit ros_superflore_generated

DESCRIPTION = "This stack contains all software necessary to build systems using both Orocos and ROS infrastructures"
AUTHOR = "Orocos Developers <orocos-dev@lists.mech.kuleuven.be>"
ROS_AUTHOR = "Ruben Smits"
HOMEPAGE = "http://ros.org/wiki/rtt_ros_integration"
SECTION = "devel"
LICENSE = "GPL-1 & BSD & LGPL-2 & GPL-1"
LIC_FILES_CHKSUM = "file://package.xml;beginline=8;endline=8;md5=162b49cfbae9eadf37c9b89b2d2ac6be"

ROS_CN = "rtt_ros_integration"
ROS_BPN = "rtt_ros_integration"

ROS_BUILD_DEPENDS = ""

ROS_BUILDTOOL_DEPENDS = " \
    catkin-native \
"

ROS_EXPORT_DEPENDS = " \
    rtt-actionlib \
    rtt-dynamic-reconfigure \
    rtt-ros \
    rtt-ros-msgs \
    rtt-rosclock \
    rtt-roscomm \
    rtt-rosdeployment \
    rtt-rosnode \
    rtt-rospack \
    rtt-rosparam \
    rtt-tf \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    rtt-actionlib \
    rtt-dynamic-reconfigure \
    rtt-ros \
    rtt-ros-msgs \
    rtt-rosclock \
    rtt-roscomm \
    rtt-rosdeployment \
    rtt-rosnode \
    rtt-rospack \
    rtt-rosparam \
    rtt-tf \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS_${PN} += "${ROS_EXEC_DEPENDS}"

SRC_URI = "https://github.com/orocos-gbp/rtt_ros_integration-release/archive/release/kinetic/rtt_ros_integration/2.9.2-1.tar.gz;downloadfilename=${ROS_SP}.tar.gz"
SRC_URI[md5sum] = "3eece653478bcdf771b43844bb54b72e"
SRC_URI[sha256sum] = "08dd5b4d6a968004ed299ab0e2f2164852ec13092916d3d6741073e2680187cf"
S = "${WORKDIR}/rtt_ros_integration-release-release-kinetic-rtt_ros_integration-2.9.2-1"

ROS_COMPONENT_TYPE = "${@ros_distro__get_component_type('rtt-ros-integration', d)}"
ROS_BUILD_TYPE = "catkin"

# Allow the above settings to be overridden.
ROS_INCLUDES_TREE := "${@ros_superflore_generated__get_includes_tree('rtt-ros-integration', d)}"
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/rtt-ros-integration/rtt-ros-integration_common.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/rtt-ros-integration/rtt-ros-integration-${PV}_common.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/rtt-ros-integration/${BPN}.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/rtt-ros-integration/${BPN}-${PV}.inc

inherit ${ROS_COMPONENT_TYPE}_component
inherit ros_${ROS_BUILD_TYPE}
