# Generated by superflore -- DO NOT EDIT
#
# Copyright 2019 Open Source Robotics Foundation

inherit ros_distro_${ROS_DISTRO}
inherit ros_superflore_generated

DESCRIPTION = "The manipulator_h_manager package     This package describes robot manager to execute manipulator_h_base_module."
AUTHOR = "Pyo <pyo@robotis.com>"
ROS_AUTHOR = "SCH <sch@robotis.com>"
HOMEPAGE = "http://wiki.ros.org/manipulator_h_manager"
SECTION = "devel"
LICENSE = "Apache-2.0"
LIC_FILES_CHKSUM = "file://package.xml;beginline=9;endline=9;md5=3dce4ba60d7e51ec64f3c3dc18672dd3"

ROS_CN = "manipulator_h"
ROS_BPN = "manipulator_h_manager"

ROS_BUILD_DEPENDS = " \
    manipulator-h-base-module \
    robotis-controller \
    roscpp \
"

ROS_BUILDTOOL_DEPENDS = " \
    catkin-native \
"

ROS_EXPORT_DEPENDS = " \
    manipulator-h-base-module \
    robotis-controller \
    roscpp \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = " \
    manipulator-h-base-module \
    robotis-controller \
    roscpp \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
# Bitbake doesn't support the "export" concept, so build them as if we needed them to build this package (even though we actually
# don't) so that they're guaranteed to have been staged should this package appear in another's DEPENDS.
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS_${PN} += "${ROS_EXEC_DEPENDS}"

SRC_URI = "https://github.com/ROBOTIS-GIT-release/ROBOTIS-MANIPULATOR-H-release/archive/release/kinetic/manipulator_h_manager/0.3.1-0.tar.gz;downloadfilename=${ROS_SP}.tar.gz"
SRC_URI[md5sum] = "feb30cf8cd76afe5cc2297296905dd81"
SRC_URI[sha256sum] = "84335dac8bad900cac41ff0f4732e59e9042af83d4185d49a3b3225947a138cb"
S = "${WORKDIR}/ROBOTIS-MANIPULATOR-H-release-release-kinetic-manipulator_h_manager-0.3.1-0"

ROS_COMPONENT_TYPE = "${@ros_distro__get_component_type('manipulator-h', d)}"
ROS_BUILD_TYPE = "catkin"

# Allow the above settings to be overridden.
ROS_INCLUDES_TREE := "${@ros_superflore_generated__get_includes_tree('manipulator-h', d)}"
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/manipulator-h/manipulator-h_common.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/manipulator-h/manipulator-h-${PV}_common.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/manipulator-h/${BPN}.inc
include ${ROS_LAYERDIR}/${ROS_INCLUDES_TREE}/manipulator-h/${BPN}-${PV}.inc

inherit ${ROS_COMPONENT_TYPE}_component
inherit ros_${ROS_BUILD_TYPE}
