# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_kilted
inherit ros_superflore_generated

DESCRIPTION = "The MRPT C++ library mrpt_tfest"
AUTHOR = "Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com>"
HOMEPAGE = "https://github.com/MRPT/"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=12;endline=12;md5=c1feec27682903a4270dbb401e443f91"

ROS_CN = "mrpt3"
ROS_BPN = "mrpt_tfest"

ROS_BUILD_DEPENDS = "\
    libeigen \
    mrpt-common \
    mrpt-poses \
    python3 \
    python3-pybind11 \
"

ROS_BUILDTOOL_DEPENDS = "\
    cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    mrpt-common \
    mrpt-poses \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    mrpt-bayes \
    mrpt-config \
    mrpt-containers \
    mrpt-core \
    mrpt-expr \
    mrpt-math \
    mrpt-random \
    mrpt-rtti \
    mrpt-serialization \
    mrpt-system \
    mrpt-typemeta \
    nanoflann-vendor \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = "\
    mrpt-common \
    mrpt-poses \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = "\
    python3-numpy \
"

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/mrpt3-release/archive/release/kilted/mrpt_tfest/3.1.3-1.tar.gz
ROS_BRANCH ?= "branch=release/kilted/mrpt_tfest"
SRC_URI = "git://github.com/ros2-gbp/mrpt3-release;${ROS_BRANCH};protocol=https"
SRCREV = "2e77fba48189594cad376a7e5bdfa1094a669e87"

ROS_BUILD_TYPE = "cmake"

inherit ros_${ROS_BUILD_TYPE}
