ROS_EXEC_DEPENDS:remove = "moveit-resources-fanuc-description"
ROS_EXEC_DEPENDS:remove = "moveit-resources-fanuc-moveit-config"
ROS_EXEC_DEPENDS:remove = "moveit-resources-panda-description"
ROS_EXEC_DEPENDS:remove = "moveit-resources-panda-moveit-config"
ROS_EXEC_DEPENDS:remove = "moveit-resources-pr2-description"
