# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "MRPT graphical user interface applications"
AUTHOR = "Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com>"
HOMEPAGE = "https://github.com/MRPT/"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=9;endline=9;md5=c1feec27682903a4270dbb401e443f91"

ROS_CN = "mrpt3"
ROS_BPN = "mrpt_apps_gui"

ROS_BUILD_DEPENDS = "\
    libeigen \
    mrpt-common \
    mrpt-graphslam \
    mrpt-kinematics \
    mrpt-libapps-gui \
    mrpt-nav \
"

ROS_BUILDTOOL_DEPENDS = "\
    cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    mrpt-common \
    mrpt-graphslam \
    mrpt-kinematics \
    mrpt-libapps-gui \
    mrpt-nav \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    cli11 \
    glfw \
    mesa \
    mrpt-bayes \
    mrpt-comms \
    mrpt-config \
    mrpt-containers \
    mrpt-core \
    mrpt-expr \
    mrpt-graphs \
    mrpt-gui \
    mrpt-hwdrivers \
    mrpt-img \
    mrpt-io \
    mrpt-libapps-cli \
    mrpt-maps \
    mrpt-math \
    mrpt-obs \
    mrpt-opengl \
    mrpt-poses \
    mrpt-random \
    mrpt-rtti \
    mrpt-serialization \
    mrpt-slam \
    mrpt-system \
    mrpt-tfest \
    mrpt-topography \
    mrpt-typemeta \
    mrpt-viz \
    nanoflann \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = "\
    mrpt-common \
    mrpt-graphslam \
    mrpt-kinematics \
    mrpt-libapps-gui \
    mrpt-nav \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/mrpt3-release/archive/release/humble/mrpt_apps_gui/3.1.2-1.tar.gz
ROS_BRANCH ?= "branch=release/humble/mrpt_apps_gui"
SRC_URI = "git://github.com/ros2-gbp/mrpt3-release;${ROS_BRANCH};protocol=https"
SRCREV = "20360dfcd64e7b38e4ce627c6d6274c8990ca771"

ROS_BUILD_TYPE = "cmake"

inherit ros_${ROS_BUILD_TYPE}
