# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_lyrical
inherit ros_superflore_generated

DESCRIPTION = "MRPT command line applications"
AUTHOR = "Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com>"
HOMEPAGE = "https://github.com/MRPT/"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=9;endline=9;md5=c1feec27682903a4270dbb401e443f91"

ROS_CN = "mrpt3"
ROS_BPN = "mrpt_apps_cli"

ROS_BUILD_DEPENDS = "\
    mrpt-common \
    mrpt-libapps-cli \
"

ROS_BUILDTOOL_DEPENDS = "\
    cmake-native \
"

ROS_EXPORT_DEPENDS = "\
    mrpt-common \
    mrpt-libapps-cli \
"

ROS_BUILDTOOL_EXPORT_DEPENDS = ""

# Propagated from the <build_export_depend>/<buildtool_export_depend> tags of the
# packages above, transitively. Bitbake has no "export" concept, so superflore
# flattens REP-149 export semantics into this recipe.
ROS_TRANSITIVE_EXPORT_DEPENDS = "\
    cli11 \
    mrpt-bayes \
    mrpt-comms \
    mrpt-config \
    mrpt-containers \
    mrpt-core \
    mrpt-expr \
    mrpt-graphs \
    mrpt-hwdrivers \
    mrpt-img \
    mrpt-io \
    mrpt-maps \
    mrpt-math \
    mrpt-obs \
    mrpt-poses \
    mrpt-random \
    mrpt-rtti \
    mrpt-serialization \
    mrpt-slam \
    mrpt-system \
    mrpt-tfest \
    mrpt-topography \
    mrpt-typemeta \
    mrpt-viz \
    nanoflann-vendor \
"

ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS = ""

ROS_EXEC_DEPENDS = "\
    mrpt-common \
    mrpt-libapps-cli \
"

# Currently informational only -- see http://www.ros.org/reps/rep-0149.html#dependency-tags.
ROS_TEST_DEPENDS = ""

DEPENDS = "${ROS_BUILD_DEPENDS} ${ROS_BUILDTOOL_DEPENDS}"
DEPENDS += "${ROS_EXPORT_DEPENDS} ${ROS_BUILDTOOL_EXPORT_DEPENDS}"
DEPENDS += "${ROS_TRANSITIVE_EXPORT_DEPENDS} ${ROS_TRANSITIVE_BUILDTOOL_EXPORT_DEPENDS}"

RDEPENDS:${PN} += "${ROS_EXEC_DEPENDS}"

# matches with: https://github.com/ros2-gbp/mrpt3-release/archive/release/lyrical/mrpt_apps_cli/3.1.3-1.tar.gz
ROS_BRANCH ?= "branch=release/lyrical/mrpt_apps_cli"
SRC_URI = "git://github.com/ros2-gbp/mrpt3-release;${ROS_BRANCH};protocol=https"
SRCREV = "d397f97a114e9f6dab10d82e32d4da55e93e1fc6"

ROS_BUILD_TYPE = "cmake"

inherit ros_${ROS_BUILD_TYPE}
